# Generated by Django 3.0.4 on 2020-04-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=3, max_digits=3)),
                ('longitude', models.DecimalField(decimal_places=3, max_digits=3)),
            ],
        ),
    ]
