# Generated by Django 3.0.4 on 2020-04-04 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_location_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='latitude',
            new_name='lat_from',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='longitude',
            new_name='lat_to',
        ),
        migrations.AddField(
            model_name='location',
            name='long_from',
            field=models.DecimalField(decimal_places=3, default=-23, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='long_to',
            field=models.DecimalField(decimal_places=3, default=-43, max_digits=5),
            preserve_default=False,
        ),
    ]
